export const home = document.querySelector(".linkHome")
export const universe = document.querySelector(".linkUniverse")
export const explore = document.querySelector(".linkExplore")
export const button = document.querySelector(".buttonHome")
export const bodyBackground = document.querySelector("body")
